[versions]
agp = "8.7.2"
androidJsonViewer = "v1.1"
androidxJunit = "1.2.1"
blurview = "version-2.0.6"
composeBom = "2024.10.01"
composeBomVersion = "2024.10.01"
core = "4.6.2"
dexkit = "2.0.2"
espressoCoreVersion = "3.6.1"
exifinterface = "1.3.7"
gson = "2.10.1"
jsonviewer = "1.0.7"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinxCoroutinesAndroid = "1.9.0"
kotlinxIoJvm = "0.1.16"
lifecycleRuntimeKtx = "2.8.7"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
kotlin = "2.0.10"
coreKtx = "1.13.1"
mmkv = "2.0.1"
multidexVersion = "2.0.1"
protobufJava = "4.28.2"
renderscript = "1.2.0-alpha01"
serializationVersion = "1.7.3"
lombok = "1.18.24"
protobuf = "4.28.2"
sealedEnum = "0.7.0"
ksp = "2.0.21-1.0.28"
recyclerview = "1.3.2"
fastjson2 = "2.0.53"

materialPreference = "2.0.0"
preference = "1.2.1"
appcompatVersion = "1.6.1"
activityCompose = "1.9.3"
kotlinVersion = "2.0.0"
materialDialog = "3.3.0"
okhttpVersion = "4.12.0"

[libraries]
android-json-viewer = { module = "com.github.pvarry:android-json-viewer", version.ref = "androidJsonViewer" }
android-tools = { module = "com.android.tools.build:gradle", version.ref = "agp" }
#noinspection SimilarGradleDependency
androidx-compose-bom-v20240902 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-renderscript = { module = "androidx.renderscript:renderscript", version.ref = "renderscript" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
#noinspection SimilarGradleDependency
blurview = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
jsonviewer = { module = "com.github.smuyyh:JsonViewer", version.ref = "jsonviewer" }
markdown-core = { module = "io.noties.markwon:core", version.ref = "core" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "4.3" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-io-jvm = { module = "org.jetbrains.kotlinx:kotlinx-io-jvm", version.ref = "kotlinxIoJvm" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationVersion" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serializationVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidexVersion" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version = "1.0.3" }
xposed = { module = "de.robv.android.xposed:api", version = "82" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "6.9.0.202403050737-r" }
sealedEnum-runtime = { module = "com.github.livefront.sealed-enum:runtime", version.ref = "sealedEnum" }
sealedEnum-ksp = { module = "com.github.livefront.sealed-enum:ksp", version.ref = "sealedEnum" }
#noinspection SimilarGradleDependency
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
glide = { module = "com.github.bumptech.glide:glide", version = "4.16.0" }
davemorrissey-subsampling-scale-image-view = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version = "3.10.0" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.8.2" }
dexlib2 = { module = "org.smali:dexlib2", version = "2.5.2" }
google-guava = { module = "com.google.guava:guava", version = "33.3.0-android" }
google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
google-protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version = "1.15.10" }

dalvik-dx = { module = "com.jakewharton.android.repackaged:dalvik-dx", version = "14.0.0_r21" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }

material-preference = { module = "dev.rikka.rikkax.material:material-preference", version.ref = "materialPreference" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
dev-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version.ref = "appcompatVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }

material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialog" }
material-dialogs-input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialDialog" }



ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version = "2.0.0" }
byte-buddy-android = { module = "net.bytebuddy:byte-buddy-android", version = "1.15.10" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.20" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }

