name: Bug report / 报告问题
description: 提交一份问题报告帮助开发者改进模块
title: "[BUG]"
labels: [ "Bug" ]


body:
- type: markdown
  attributes:
    value: |
      感谢给 ouo 汇报问题！
      为了使我们更好地帮助你，请提供以下信息。
- type: textarea
  attributes:
    label: 复现步骤 / Steps to reproduce
    placeholder: |
      1.
      2.
      3.
  validations:
    required: true
- type: textarea
  attributes:
    label: 预期行为 / Expected behaviour
    placeholder: 正常情况下应该发生什么 / Tell us what should happen
  validations:
    required: true
- type: textarea
  attributes:
    label: 实际行为 / Actual behaviour
    description: 如果含有截图，个人信息注意打码保护
    placeholder: 实际上发生了什么 / Tell us what happens instead
  validations:
    required: true

- type: input
  attributes:
    label: 你使用的 Xposed 框架 / Xposed Framework you used
  validations:
    required: true
- type: input
  attributes:
    label: 你使用的安卓系统版本 / Your Android version
  validations:
    required: true
- type: input
  attributes:
    label: QQ 版本 / QQ Version
    description: QQ 版本 / QQ Version
  validations:
    required: true
- type: input
  attributes:
    label: 模块版本 / Module Version
    description: 不要使用“最新版”。给出详细版本号，否则 issue 将被关闭。在 https://t.me/ono_ci 获取最新 CI 版本。 / Don't use 'latest'. Specify actual version with 4 digits, otherwise your issue will be closed. Get the latest CI version from https://t.me/ono_ci .
  validations:
    required: true
- type: checkboxes
  id: latest
  attributes:
    label: 版本和其他要求 / Version and Other Requirements
    options:
    - label: 我正在使用最新 CI 调试版本且启用日志记录 / I am using latest debug CI version of ono and enable log
      required: false
    - label: 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
      required: false
    - label: 我已经在 [Issue Tracker](https://github.com/cwuom/ono/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
      required: true
    - label: 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
      required: true
    - label: 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
      required: true

- type: textarea
  attributes:
    label: 日志 / Logs
    description: 因错误追踪系统不完善，此项非必填。如果条件允许，可使用 LogFox 抓取运行日志，或是上传 /storage/emulated/0/Android/data/com.tencent.mobileqq/ONO/log/ErrorLog/ 内的日志。
    placeholder: 将日志粘贴到此处或者点击文本框底栏上传日志文件。 / Paste logs here or upload logs by clicking the bar on the bottom.
  validations:
    required: false

- type: textarea
  id: extra-desc
  attributes:
    label: 补充说明（可选） / Additional information (optional)